### ISSUE TITLE
Audio is not seekable

### ISSUE THREAD

**Issue by azmke** [azmke/kalita-server#3]
As a user of the [kalita-js](https://github.com/azmke/kalita-js) front end, I am unable to seek within the audio file.

However, the cause of the problem is not in the front end, but in the fact that the server does not support seeking as the request header `Range` is ignored.

Please add support for audio seeking.

**Comment by azmke** [comment]
More information on this topic:

https://stackoverflow.com/questions/10583931/cant-seek-html5-video-or-audio-in-chrome

**Comment by doblut** [comment]
Fixed in Commit f20c3716a7e5e2aaed9e3f4e79139fb797418a5d
