### ISSUE TITLE
Rename generated audio file

### ISSUE THREAD

**Issue by azmke** [azmke/kalita-server#5]
When I, as a user, download the voice output, I get a file named `speak`, with no file extension. In order to open the file on my computer, I must first rename it to `speak.mp3`. I wish that I can open the file directly after downloading.

Naming suggestion: `speak-2021-01-22-12-12-46.mp3`

**Comment by doblut** [comment]
Added in commit a36d2c30ae02577708d83c33bc4f5a05c018556c
